# Generated by Django 4.0.3 on 2022-06-20 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizwiz', '0002_upvote_downvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dateposted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='dateposted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
