# Generated by Django 4.0.3 on 2022-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizwiz', '0003_answer_dateposted_question_dateposted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='dateposted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='dateposted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
