# Generated by Django 4.0.3 on 2022-08-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizwiz', '0002_answer_dateposted_answer_likes_answer_user_and_more'),
        ('bizwiz', '0005_answer_user_question_user'),
    ]

    operations = [
    ]
